remote: origin
target-branch: my-refs
helm-extra-args: --timeout 180s
chart-yaml-schema: .github/chart_schema.yaml
chart-dirs:
  - charts/stable
excluded-charts: []
chart-repos:
  - truecharts=https://charts.truecharts.org
  - truecharts-library=https://library-charts.truecharts.org
  - truecharts-deps=https://deps.truecharts.org
