remote: origin
target-branch: my-refs
chart-yaml-schema: .github/chart_schema.yaml
helm-extra-args: --timeout 120s
chart-dirs:
  - charts/stable
excluded-charts: []
chart-repos:
  - truecharts=https://charts.truecharts.org
  - truecharts-library=https://library-charts.truecharts.org
  - truecharts-deps=https://deps.truecharts.org
