apiVersion: v2
name: cert-manager-webhook-pdns
version: 1.1.4
description: Cert Manager Webhook for PowerDNS.
type: application
home: https://github.com/cyr-ius/cert-manager-webhook-pdns
maintainers:
  - name: Cyr-ius
    email: webmaster@ipocus.net
    url: https://ipocus.net
appVersion: v1.1.4
annotations:
  max_scale_version: 23.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: home-automation
  truecharts.org/max_helm_version: "3.13"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
