name: "Prune Old Releases"

on:
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    name: "prune old releases"
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
              fetch-depth: 0
      - uses: dev-drprasad/delete-older-releases@dfbe6be2a006e9475dfcbe5b8d201f1824c2a9fe # v0.3.4
        with:
          keep_latest: 200
          keep_min_download_counts: 1 # Optional parameters
          delete_expired_data: 10 # Optional parameters
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          min-versions-to-keep: 200
